version: '3.8'

services:
  google-captcha-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    container_name: google-captcha-app
